spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: "jdbc:mysql://localhost:3306/community"
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  jpa.open-in-view: false

jwt:
  secret: ${secretKey}
  expiration: 86400000
